### ISSUE TITLE
草稿模式下面，中文摘要和英文摘要页面有点问题，附一个建议

### ISSUE THREAD

**Issue by liuqt** [hust-latex/hustthesis#11]
草稿模式下面，中文摘要和英文摘要页面有点问题，中文摘要一词和英文摘要单词如果只看这两页的话，二者并不在一个水平线上，也就是这个页面不一致。
附一个建议，不要使用subcaption，caption已经包含subcaption的全部功能了。把subcaption唤做subfigure倒是很实用。

**Comment by xu-cheng** [comment]
我不大可能对这个模板做任何样式的更改。不过欢迎你提交 Pull Request。

选择使用subcaption是正确的，因为subfigure是已经淘汰的宏包。 c.f. http://en.wikibooks.org/wiki/LaTeX/Floats,_Figures_and_Captions#Subfloats
