### ISSUE TITLE
段与段之间的间隔太大了吧

### ISSUE THREAD

**Issue by nejyeah** [hust-latex/hustthesis#14]
非常感谢能有这么一个专门针对华科的latex模板，但我简单用了以下后发现段与段之间的距离太大了，Latex里面貌似要以空行来分段，但是这样之后段一段之间的距离特别大，怎么调节这个了

**Comment by xu-cheng** [comment]
模板里，段距已经被设置为[0pt](https://github.com/hust-latex/hustthesis/blob/master/hustthesis/hustthesis.dtx#L1305)。所以请检查是否是你文档代码的问题。

**Comment by xavierwoo** [comment]
我的感觉是，如果你几段话不能填满一页，后面又接了图表，加上这个图表会超过一页的时候，容易出现段与段之间间隔很大。
这个时候编译效果会变成图在第二页，前面几段平均分布，就显得段间距很大。
