### ISSUE TITLE
不能在mac下使用

### ISSUE THREAD

**Issue by xavierwoo** [hust-latex/hustthesis#15]
您好，感谢您制作了华科的博士论文模版。

但是好像不能在Mac下使用的样子。

我已经使用make unpack命令生成了cls文件，但是无法编译tex。
<img width="1440" alt="2016-01-28 12 02 04" src="https://cloud.githubusercontent.com/assets/4199897/12652148/7aae1e68-c5b7-11e5-8163-9700908c6b4c.png">

我使用的是TexLive + texstudio

可以告诉我是哪里有问题嘛？
谢谢！

**Comment by xu-cheng** [comment]
See http://hust-latex.github.io/faqs

**Comment by xavierwoo** [comment]
谢！已解决。
但是texstudio不能显示中文也是伤感。。。。。
这个应该是IDE的问题

**Comment by xu-cheng** [comment]
> 但是texstudio不能显示中文也是伤感

建议使用TeXshop。
