### ISSUE TITLE
目录格式问题

### ISSUE THREAD

**Issue by fomy** [hust-latex/hustthesis#16]
1. 英文摘要的页码没有在目录中显示；
2. 一级标题，如“1 绪论”后面不显示页码；
3. 目录的页码显示增加括号为“（1）”

请问这些应该如何修改呢？谢谢。

**Comment by fomy** [comment]
第一个问题已解决。
只需要如下增加 \addcontentsline{toc}{chapter}{\HUST@enabstractname}

  \ifthenelse{\equal{\HUST@language}{chinese}}{
    \addcontentsline{toc}{chapter}{\HUST@zhabstractnamenospace}
    \addcontentsline{toc}{chapter}{\HUST@enabstractname}
  }

**Comment by fomy** [comment]
后两个问题已用 \titlecontents 解决。

**Comment by bdgong** [comment]
请问关于 ' 目录的页码显示增加括号为“（1）” ' 问题\titlecontents具体命令是什么？
