### ISSUE TITLE
如何修改附录的格式？

### ISSUE THREAD

**Issue by fomy** [hust-latex/hustthesis#17]
现在的附录格式是“附录 A 攻读学位期间发表的学术论文”，在目录里显示的是“A 附录 攻读学位期间发表的学术论文”。

请问如何修改为“附录 1 攻读学位期间发表的学术论文”，在目录里也显示为“附录 1 攻读学位期间发表的学术论文”

**Comment by xu-cheng** [comment]
Try
```latex
\appendix
\renewcommand{\thechapter}{\arabic{chapter}}
```

**Comment by fomy** [comment]
谢谢。

目录里现在变成了“1 附录 攻读学位期间发表的学术论文”，但是我想变成“附录 1 攻读学位期间发表的学术论文”。

**Comment by xu-cheng** [comment]
我测试的是正常的啊。 建议你先清空LaTeX的临时文件，再试一次。

**Comment by fomy** [comment]
目录里面显示的也是正常的吗？

**Comment by xu-cheng** [comment]
![2016-04-13 2 20 33](https://cloud.githubusercontent.com/assets/3105373/14484426/fbbbc404-0182-11e6-8a4c-3c23dd56e530.png)
<img width="562" alt="2016-04-13 2 20 57" src="https://cloud.githubusercontent.com/assets/3105373/14484430/02f4a790-0183-11e6-859d-7d19a1b4198a.png">

**Comment by fomy** [comment]
抱歉，是我用  \titlecontents 增加虚线的缘故，如下，
  \titlecontents{chapter}
              [1.5em]
              {\bf}
              {\contentslabel{1.5em}}
              {}
              {\normalfont\dotfill\textrm{\contentspage[(\thecontentspage)]}}
              [\addvspace{0.5pc}]

加上这段代码，就变成“1 附录”了。对这个不太熟，还没找到解决方法。

**Comment by xu-cheng** [comment]
不是很清楚你想加什么样的虚线。如下是模板在附录里使用的titleformat代码。
``` latex
  \titleformat{\chapter}
  {
    \bfseries\HEI
    \centering
    \changefont{size=18pt}
  }
  {\appendixname\,\thechapter}
  {1em}
  {}

**Comment by fomy** [comment]
模版的目录二级标题用点填充了，但是一级标题没有，我想为附录、参考文献都填充点。

**Comment by xu-cheng** [comment]
建议使用[tocloft](http://mirrors.ctan.org/macros/latex/contrib/tocloft/tocloft.pdf)来修改目录式样

**Comment by fomy** [comment]
谢谢。用\cftchapleader似乎可以达到效果。
