### ISSUE TITLE
关于生成目录的页码格式问题

### ISSUE THREAD

**Issue by raytaylorlin** [hust-latex/hustthesis#18]
导师说目录中大章后面不写页码，小节的页码用小括号括起来，像下面这样。请问下模板应该怎么改？
```
1. 绪论                                                  【←这里不显示页码】
  1.1 课题研究背景与意义 ............................... (1)
  1.2 国内外研究现状.....................................(2)
```

**Comment by xu-cheng** [comment]
Please refer to [tocloft](http://mirrors.ctan.org/macros/latex/contrib/tocloft/tocloft.pdf) for DIYing table of contents.

**Comment by raytaylorlin** [comment]
明白了，使用以下代码即可
```
\let\origcftsecpagefont\cftsecpagefont
\let\origcftsecafterpnum\cftsecafterpnum
\renewcommand{\cftsecpagefont}{(\origcftsecpagefont}
\renewcommand{\cftsecafterpnum}{\origcftsecafterpnum)}

\addtocontents{toc}{\cftpagenumbersoff{chapter}}
```
[How to add text before page number using tocloft?](http://tex.stackexchange.com/questions/305149/how-to-add-text-before-page-number-using-tocloft)

**Comment by bdgong** [comment]
这样的确可以去掉chaper的页码，以及为section加括号，但是摘要和参考文献等页码也没有了啊？
