### ISSUE TITLE
关于行距的问题

### ISSUE THREAD

**Issue by xavierwoo** [hust-latex/hustthesis#19]
学校学位论文要求说行距不小于三分之二字高，现在的模版似乎没有这么大的行距。请问有调行距的命令么？

**Comment by xu-cheng** [comment]
[`\changefont{linespread=xx}`](http://texdoc.net/texmf-dist/doc/latex/interfaces/interfaces.pdf)

**Comment by xavierwoo** [comment]
谢谢！
