### ISSUE TITLE
./hustthesis.cls:188: Undefined control sequence. l.188 \pagewidth =\paperwidth

### ISSUE THREAD

**Issue by ji759823501** [hust-latex/hustthesis#24]
您好，我已换成2016版本，还是是同样的错误。。。
) (/usr/local/texlive/2016/texmf-dist/tex/xelatex/xecjk/xunicode-extra.def)
(/usr/local/texlive/2016/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))
(/usr/local/texlive/2016/texmf-dist/tex/latex/zhnumber/zhnumber.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/zhnumber/zhnumber-utf8.cfg))
(/usr/local/texlive/2016/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
./hustthesis.cls:188: Undefined control sequence.
l.188 \pagewidth
=\paperwidth

**Comment by xu-cheng** [comment]
Dupe with #23
