### ISSUE TITLE
关于毕业设计论文生成目录不包含\subsection和更低级别的子标题

### ISSUE THREAD

**Issue by KuiWei004** [hust-latex/hustthesis#27]
学长你好！我是黑晓军的学生，我最近在用该模板写论文，发现\tableofcontents生成的目录没有二级及以下级别的子标题，请问这个是模板中设置的吗？在哪设置的？谢谢

**Comment by xu-cheng** [comment]
根据格式要求，目录是不显示这些子标题的。

如果你想更改，可以在导言区加入
```latex
\setcounter{tocdepth}{<depth>}
```
其中`<depth>` 控制标题显示深度。

**Comment by KuiWei004** [comment]
谢谢学长！




隗 巍


在2017年05月12日 14:36，Xu Cheng<notifications@github.com> 写道：

根据格式要求，目录是不显示这些子标题的。

如果你想更改，可以在导言区加入

\setcounter{tocdepth}{<depth>}

其中<depth> 控制标题显示深度。
