### ISSUE TITLE
中文段落首行缩进不足两个字符

### ISSUE THREAD

**Issue by bdgong** [hust-latex/hustthesis#29]
![selection_339](https://user-images.githubusercontent.com/11557978/39235760-616a8884-48a9-11e8-8329-af1b1fca2218.png)

**Comment by xu-cheng** [comment]
你可以自行调节大小，默认设置如下：
```latex
\setlength{\parindent}{2em}
```

**Comment by bdgong** [comment]
嗯，样式文件里的确定义了这个缩进值，但是为什么不能按照习惯让缩进值为中文的两个字符呢？

**Comment by xu-cheng** [comment]
`2em` 表示2个m字符宽度。 至于为什么不是中文的两个字符宽度，应该是因为中英文字体不同的问题。所以建议你使用上面的命令进行微调。

**Comment by bdgong** [comment]
嗯明白你的意思，谢谢。另外，请问一下，xeCJK目前是没有提供能够设置两个中文字符宽度的选项吗
