### ISSUE TITLE
Ubuntu 16.04.5 LTS 编译时标题序号丢失

### ISSUE THREAD

**Issue by PercyLau** [hust-latex/hustthesis#31]
您好，

当前版本在Ubuntu 16.04.5 LTS XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015/Debian) 下编译时，生成的pdf文件的所有标题的序号都消失了。在Windows环境下正常。请问，有没有什么解决办法？

祝好，
Percy

**Comment by xu-cheng** [comment]
> TeX Live 2015

能否测试最新的texlive 2018

**Comment by PercyLau** [comment]
谢谢, 在Tex Live 2017下测试标题正常。Tex Live 2018版本没有测试，估计也没有问题。但是TeX Live 2015是Ubuntu 16.04的默认版本，会不会有其他影响？

**Comment by xu-cheng** [comment]
一般不建议使用apt安装texlive。

latex经常有宏包冲突，所以一般推荐使用最新版本。
