### ISSUE TITLE
Appendix区域后面无法使用\input{filename}和\include{filename}

### ISSUE THREAD

**Issue by PercyLau** [hust-latex/hustthesis#32]
Hi,

我发现在中文环境下，\appendix后面不能使用\input{}和\include{}命令。强行编译的话，中文会变成乱码，英文没有问题。
\bibliography{ref}

\appendix
\chapter{证明}\label{appendix:A}
\input{Appendix.tex} % 在Appendix.tex有中文符号

latex系统信息：
texlive 2017 windows
Windows 10 pro

祝好，
Percy

**Comment by xu-cheng** [comment]
请问有编译错误的log吗？

**Comment by PercyLau** [comment]
Invalid UTF-8 byte or sequence at line 2 replaced by U+FFFD.
Invalid UTF-8 byte or sequence at line 2 replaced by U+FFFD.

! Text line contains an invalid character.
l.2 ...�����������¾���^^?
                                                  ³��ֳ�ը�����...
A funny symbol that I can't read has just been input.
Continue, and I'll forget that it ever happened.

! Text line contains an invalid character.
l.2 ...24��ȫ���ƶ¯��¾���^^?
                                                  ½«³¬¹�77°¬¿���...
A funny symbol that I can't read has just been input.
Continue, and I'll forget that it ever happened.

Invalid UTF-8 byte or sequence at line 4 replaced by U+FFFD.
Invalid UTF-8 byte or sequence at line 4 replaced by U+FFFD.
Invalid UTF-8 byte or sequence at line 4 replaced by U+FFFD.
Invalid UTF-8 byte or sequence at line 4 replaced by U+FFFD.
Invalid UTF-8 byte or sequence at line 4 replaced by U+FFFD.
================================================
感觉似乎是编码问题。完整的log文件请参考dropbox链接：https://www.dropbox.com/s/35qnasicbte5kd4/hustthesis_error_log.txt?dl=0

**Comment by xu-cheng** [comment]
请尝试这些方法：
* 使用lualatex 编译
* 请升级texlive至最新的2018版
* 请检查文件编码，特别是是否有看不见的非法字符

**Comment by PercyLau** [comment]
在main.tex文件开头加入：
% !TEX program = xelatex
% !TeX encoding = UTF-8
可以解决这个问题。
