### ISSUE TITLE
参考文献样式求助

### ISSUE THREAD

**Issue by nujabse** [hust-latex/hustthesis#38]
有一些文献是已经 online 了，但是并没有出具体的卷、页码，想要引用这些文献怎么实现呢？

**Comment by PercyLau** [comment]
可以参考各出版单位给出的样式手册，手动修订\bibitem, 例如，参考IEEE Reference Guide 2019.

**Comment by nujabse** [comment]
按照您的建议手动修改条目就好了，感谢！

**Comment by szrlee** [comment]
> 按照您的建议手动修改条目就好了，感谢！

可以能举个例子嘛？
